run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - revive
    - gofmt
    - goimports

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true